<?php

namespace App\NativeComponents\Concerns;

use App\Icons\Android;
use App\Icons\Ios;

trait HasListingData
{
    /**
     * @return array<int, array{title: string, location: string, imageUrl: string, images: array<string>, price: int, rating: float, reviewCount: int, category: string, host: string, hostAvatarUrl: string, hostIsSuperhost: bool, hostYears: int, description: string, amenities: array<int, array{icon: string, label: string}>, type: string, guests: int, bedrooms: int, beds: int, bathrooms: float, dates: string, distance: string, highlights: array<int, array{icon: string, title: string, subtitle: string}>}>
     */
    public static function listings(): array
    {
        return [
            [
                'title' => 'Oceanfront Villa with Infinity Pool',
                'location' => 'Malibu, California',
                'imageUrl' => 'https://picsum.photos/seed/abnb1/800/600',
                'images' => [
                    'https://picsum.photos/seed/abnb1/800/600',
                    'https://picsum.photos/seed/abnb1b/800/600',
                    'https://picsum.photos/seed/abnb1c/800/600',
                    'https://picsum.photos/seed/abnb1d/800/600',
                    'https://picsum.photos/seed/abnb1e/800/600',
                ],
                'price' => 350,
                'rating' => 4.9,
                'reviewCount' => 128,
                'category' => 'Beachfront',
                'host' => 'Sarah',
                'hostAvatarUrl' => 'https://i.pravatar.cc/150?u=abnbhost1',
                'hostIsSuperhost' => true,
                'hostYears' => 6,
                'description' => "Wake up to breathtaking ocean views in this stunning beachfront villa. Features an infinity pool overlooking the Pacific, open-concept living, and direct beach access.\n\nThe space\nThis 3-bedroom villa spans 2,400 sq ft with floor-to-ceiling windows throughout. The main living area opens directly onto a seaside terrace with an infinity pool. A fully equipped gourmet kitchen makes entertaining a breeze.\n\nGuest access\nYou'll have the entire villa to yourself, including the pool, private beach path, and two-car garage.",
                'amenities' => [
                    ['ios' => Ios::Wifi, 'android' => Android::Wifi, 'label' => 'Wifi'],
                    ['ios' => Ios::FigurePoolSwim, 'android' => Android::Pool, 'label' => 'Pool'],
                    ['ios' => Ios::RefrigeratorFill, 'android' => Android::Kitchen, 'label' => 'Kitchen'],
                    ['ios' => Ios::Parkingsign, 'android' => Android::LocalParking, 'label' => 'Free parking on premises'],
                    ['ios' => Ios::Snowflake, 'android' => Android::AcUnit, 'label' => 'Air conditioning'],
                    ['ios' => Ios::WasherFill, 'android' => Android::LocalLaundryService, 'label' => 'Washer'],
                    ['ios' => Ios::Tv, 'android' => Android::Tv, 'label' => '65" HDTV with Netflix'],
                    ['ios' => Ios::FlameFill, 'android' => Android::OutdoorGrill, 'label' => 'BBQ grill'],
                    ['ios' => Ios::ChairLoungeFill, 'android' => Android::Deck, 'label' => 'Patio or balcony'],
                    ['ios' => Ios::BeachUmbrellaFill, 'android' => Android::BeachAccess, 'label' => 'Beach access'],
                ],
                'type' => 'Entire home',
                'guests' => 6,
                'bedrooms' => 3,
                'beds' => 4,
                'bathrooms' => 2.5,
                'dates' => 'Mar 2–7',
                'distance' => '48 miles away',
                'highlights' => [
                    ['ios' => Ios::DoorLeftHandClosed, 'android' => Android::DoorFront, 'title' => 'Self check-in', 'subtitle' => 'Check yourself in with the lockbox.'],
                    ['ios' => Ios::StarFill, 'android' => Android::Star, 'title' => 'Sarah is a Superhost', 'subtitle' => 'Superhosts are experienced, highly rated Hosts.'],
                    ['ios' => Ios::CalendarBadgeCheckmark, 'android' => Android::EventAvailable, 'title' => 'Free cancellation before Feb 26', 'subtitle' => ''],
                ],
            ],
            [
                'title' => 'Cozy Mountain A-Frame',
                'location' => 'Aspen, Colorado',
                'imageUrl' => 'https://picsum.photos/seed/abnb2/800/600',
                'images' => [
                    'https://picsum.photos/seed/abnb2/800/600',
                    'https://picsum.photos/seed/abnb2b/800/600',
                    'https://picsum.photos/seed/abnb2c/800/600',
                    'https://picsum.photos/seed/abnb2d/800/600',
                    'https://picsum.photos/seed/abnb2e/800/600',
                ],
                'price' => 220,
                'rating' => 4.8,
                'reviewCount' => 95,
                'category' => 'Cabins',
                'host' => 'Jake',
                'hostAvatarUrl' => 'https://i.pravatar.cc/150?u=abnbhost2',
                'hostIsSuperhost' => true,
                'hostYears' => 4,
                'description' => "A charming A-frame cabin nestled in the Rocky Mountains. Floor-to-ceiling windows frame stunning mountain vistas. Wood-burning fireplace, hot tub on the deck, and ski-in/ski-out access during winter.\n\nThe space\nThis iconic A-frame features an open loft bedroom with mountain views, a cozy living room with vaulted ceilings, and a fully stocked kitchen. The wraparound deck includes a private hot tub.\n\nGuest access\nEntire cabin is yours. Ski locker and boot dryer included.",
                'amenities' => [
                    ['ios' => Ios::Wifi, 'android' => Android::Wifi, 'label' => 'Wifi'],
                    ['ios' => Ios::BathtubFill, 'android' => Android::HotTub, 'label' => 'Private hot tub'],
                    ['ios' => Ios::FlameFill, 'android' => Android::Fireplace, 'label' => 'Indoor fireplace'],
                    ['ios' => Ios::RefrigeratorFill, 'android' => Android::Kitchen, 'label' => 'Kitchen'],
                    ['ios' => Ios::Parkingsign, 'android' => Android::LocalParking, 'label' => 'Free parking on premises'],
                    ['ios' => Ios::ThermometerMedium, 'android' => Android::Thermostat, 'label' => 'Heating'],
                    ['ios' => Ios::Tv, 'android' => Android::Tv, 'label' => '55" HDTV with streaming'],
                    ['ios' => Ios::FigureSkiingDownhill, 'android' => Android::DownhillSkiing, 'label' => 'Ski-in/ski-out'],
                    ['ios' => Ios::ChairLoungeFill, 'android' => Android::Deck, 'label' => 'Deck with mountain views'],
                    ['ios' => Ios::CupAndSaucerFill, 'android' => Android::CoffeeMaker, 'label' => 'Coffee maker'],
                ],
                'type' => 'Entire home',
                'guests' => 4,
                'bedrooms' => 2,
                'beds' => 2,
                'bathrooms' => 1,
                'dates' => 'Mar 10–15',
                'distance' => '920 miles away',
                'highlights' => [
                    ['ios' => Ios::DoorLeftHandClosed, 'android' => Android::DoorFront, 'title' => 'Self check-in', 'subtitle' => 'Check yourself in with the smart lock.'],
                    ['ios' => Ios::StarFill, 'android' => Android::Star, 'title' => 'Jake is a Superhost', 'subtitle' => 'Superhosts are experienced, highly rated Hosts.'],
                    ['ios' => Ios::CalendarBadgeCheckmark, 'android' => Android::EventAvailable, 'title' => 'Free cancellation before Mar 3', 'subtitle' => ''],
                ],
            ],
            [
                'title' => 'Rustic Lakeside Cabin',
                'location' => 'Lake Tahoe, Nevada',
                'imageUrl' => 'https://picsum.photos/seed/abnb3/800/600',
                'images' => [
                    'https://picsum.photos/seed/abnb3/800/600',
                    'https://picsum.photos/seed/abnb3b/800/600',
                    'https://picsum.photos/seed/abnb3c/800/600',
                    'https://picsum.photos/seed/abnb3d/800/600',
                    'https://picsum.photos/seed/abnb3e/800/600',
                ],
                'price' => 185,
                'rating' => 4.7,
                'reviewCount' => 73,
                'category' => 'Lakefront',
                'host' => 'Emma',
                'hostAvatarUrl' => 'https://i.pravatar.cc/150?u=abnbhost3',
                'hostIsSuperhost' => false,
                'hostYears' => 2,
                'description' => "Charming cabin right on the lake with a private dock and kayaks included. Enjoy sunsets from the wraparound porch or cozy up by the stone fireplace.\n\nThe space\nA 2-bedroom cabin with rustic charm and modern comforts. The open-plan living and dining area looks out over the lake. Full kitchen with everything you need.\n\nGuest access\nEntire cabin including private dock, kayaks, and fire pit area.",
                'amenities' => [
                    ['ios' => Ios::Wifi, 'android' => Android::Wifi, 'label' => 'Wifi'],
                    ['ios' => Ios::RefrigeratorFill, 'android' => Android::Kitchen, 'label' => 'Kitchen'],
                    ['ios' => Ios::Oar2Crossed, 'android' => Android::Kayaking, 'label' => 'Kayaks included'],
                    ['ios' => Ios::FlameFill, 'android' => Android::Fireplace, 'label' => 'Indoor fireplace'],
                    ['ios' => Ios::FlameFill, 'android' => Android::OutdoorGrill, 'label' => 'BBQ grill'],
                    ['ios' => Ios::Parkingsign, 'android' => Android::LocalParking, 'label' => 'Free parking on premises'],
                    ['ios' => Ios::Tv, 'android' => Android::Tv, 'label' => 'HDTV'],
                    ['ios' => Ios::DropFill, 'android' => Android::Water, 'label' => 'Waterfront'],
                    ['ios' => Ios::ChairLoungeFill, 'android' => Android::Deck, 'label' => 'Wraparound porch'],
                    ['ios' => Ios::FlameFill, 'android' => Android::LocalFireDepartment, 'label' => 'Fire pit'],
                ],
                'type' => 'Entire home',
                'guests' => 5,
                'bedrooms' => 2,
                'beds' => 3,
                'bathrooms' => 1.5,
                'dates' => 'Apr 1–6',
                'distance' => '195 miles away',
                'highlights' => [
                    ['ios' => Ios::DoorLeftHandClosed, 'android' => Android::DoorFront, 'title' => 'Self check-in', 'subtitle' => 'Check yourself in with the keypad.'],
                    ['ios' => Ios::PhotoFill, 'android' => Android::Landscape, 'title' => 'Lakefront', 'subtitle' => 'This property is right on the lake.'],
                    ['ios' => Ios::CalendarBadgeCheckmark, 'android' => Android::EventAvailable, 'title' => 'Free cancellation before Mar 25', 'subtitle' => ''],
                ],
            ],
            [
                'title' => 'Modern Treehouse Retreat',
                'location' => 'Portland, Oregon',
                'imageUrl' => 'https://picsum.photos/seed/abnb4/800/600',
                'images' => [
                    'https://picsum.photos/seed/abnb4/800/600',
                    'https://picsum.photos/seed/abnb4b/800/600',
                    'https://picsum.photos/seed/abnb4c/800/600',
                    'https://picsum.photos/seed/abnb4d/800/600',
                    'https://picsum.photos/seed/abnb4e/800/600',
                ],
                'price' => 175,
                'rating' => 4.95,
                'reviewCount' => 210,
                'category' => 'OMG!',
                'host' => 'Marcus',
                'hostAvatarUrl' => 'https://i.pravatar.cc/150?u=abnbhost4',
                'hostIsSuperhost' => true,
                'hostYears' => 8,
                'description' => "Elevated among old-growth cedars, this architectural treehouse combines modern luxury with nature immersion. Glass walls, rainforest shower, and a suspended deck for stargazing.\n\nThe space\nA truly unique space perched 30 feet above the forest floor. The studio-style interior features floor-to-ceiling glass, a queen bed with heated mattress pad, and a compact kitchenette.\n\nGuest access\nThe entire treehouse and surrounding 2-acre property.",
                'amenities' => [
                    ['ios' => Ios::Wifi, 'android' => Android::Wifi, 'label' => 'Wifi'],
                    ['ios' => Ios::RefrigeratorFill, 'android' => Android::Kitchen, 'label' => 'Kitchenette'],
                    ['ios' => Ios::ThermometerMedium, 'android' => Android::Thermostat, 'label' => 'Heating'],
                    ['ios' => Ios::ChairLoungeFill, 'android' => Android::Deck, 'label' => 'Suspended deck'],
                    ['ios' => Ios::TreeFill, 'android' => Android::Forest, 'label' => 'Nature views'],
                    ['ios' => Ios::ShowerFill, 'android' => Android::Shower, 'label' => 'Outdoor rainforest shower'],
                    ['ios' => Ios::CupAndSaucerFill, 'android' => Android::CoffeeMaker, 'label' => 'Coffee maker'],
                    ['ios' => Ios::Parkingsign, 'android' => Android::LocalParking, 'label' => 'Free parking on premises'],
                ],
                'type' => 'Entire home',
                'guests' => 2,
                'bedrooms' => 1,
                'beds' => 1,
                'bathrooms' => 1,
                'dates' => 'Mar 15–20',
                'distance' => '635 miles away',
                'highlights' => [
                    ['ios' => Ios::DoorLeftHandClosed, 'android' => Android::DoorFront, 'title' => 'Self check-in', 'subtitle' => 'Check yourself in with the lockbox.'],
                    ['ios' => Ios::StarFill, 'android' => Android::Star, 'title' => 'Marcus is a Superhost', 'subtitle' => 'Superhosts are experienced, highly rated Hosts.'],
                    ['ios' => Ios::Sparkles, 'android' => Android::AutoAwesome, 'title' => 'Guest favorite', 'subtitle' => 'One of the most loved homes on Airbnb.'],
                ],
            ],
            [
                'title' => 'Downtown Luxury Loft',
                'location' => 'New York, New York',
                'imageUrl' => 'https://picsum.photos/seed/abnb5/800/600',
                'images' => [
                    'https://picsum.photos/seed/abnb5/800/600',
                    'https://picsum.photos/seed/abnb5b/800/600',
                    'https://picsum.photos/seed/abnb5c/800/600',
                    'https://picsum.photos/seed/abnb5d/800/600',
                    'https://picsum.photos/seed/abnb5e/800/600',
                ],
                'price' => 275,
                'rating' => 4.6,
                'reviewCount' => 156,
                'category' => 'Trending',
                'host' => 'Diana',
                'hostAvatarUrl' => 'https://i.pravatar.cc/150?u=abnbhost5',
                'hostIsSuperhost' => false,
                'hostYears' => 3,
                'description' => "Sleek industrial loft in the heart of Manhattan. Exposed brick, designer furnishings, and skyline views. Walking distance to top restaurants, galleries, and Central Park.\n\nThe space\nThis 1,200 sq ft loft features 14-foot ceilings, original exposed brick, polished concrete floors, and massive arched windows. The open layout includes a dedicated workspace.\n\nGuest access\nEntire loft plus building amenities including gym and rooftop.",
                'amenities' => [
                    ['ios' => Ios::Wifi, 'android' => Android::Wifi, 'label' => 'Wifi'],
                    ['ios' => Ios::Snowflake, 'android' => Android::AcUnit, 'label' => 'Air conditioning'],
                    ['ios' => Ios::WasherFill, 'android' => Android::LocalLaundryService, 'label' => 'Washer'],
                    ['ios' => Ios::DumbbellFill, 'android' => Android::FitnessCenter, 'label' => 'Gym in building'],
                    ['ios' => Ios::LockShieldFill, 'android' => Android::Security, 'label' => 'Doorman'],
                    ['ios' => Ios::RefrigeratorFill, 'android' => Android::Kitchen, 'label' => 'Kitchen'],
                    ['ios' => Ios::Tv, 'android' => Android::Tv, 'label' => '75" HDTV with cable'],
                    ['ios' => Ios::ArrowUpAndDownSquareFill, 'android' => Android::Elevator, 'label' => 'Elevator'],
                    ['ios' => Ios::Laptopcomputer, 'android' => Android::Laptop, 'label' => 'Dedicated workspace'],
                    ['ios' => Ios::TshirtFill, 'android' => Android::Iron, 'label' => 'Iron'],
                ],
                'type' => 'Entire loft',
                'guests' => 4,
                'bedrooms' => 1,
                'beds' => 2,
                'bathrooms' => 1,
                'dates' => 'Mar 22–27',
                'distance' => '2,451 miles away',
                'highlights' => [
                    ['ios' => Ios::DoorLeftHandClosed, 'android' => Android::DoorFront, 'title' => 'Self check-in', 'subtitle' => 'Check yourself in with the building doorman.'],
                    ['ios' => Ios::PhotoFill, 'android' => Android::Landscape, 'title' => 'Great location', 'subtitle' => '95% of recent guests gave the location a 5-star rating.'],
                    ['ios' => Ios::Laptopcomputer, 'android' => Android::Laptop, 'title' => 'Dedicated workspace', 'subtitle' => 'A common area with wifi that is well-suited for working.'],
                ],
            ],
            [
                'title' => 'Tropical Beach Bungalow',
                'location' => 'Maui, Hawaii',
                'imageUrl' => 'https://picsum.photos/seed/abnb6/800/600',
                'images' => [
                    'https://picsum.photos/seed/abnb6/800/600',
                    'https://picsum.photos/seed/abnb6b/800/600',
                    'https://picsum.photos/seed/abnb6c/800/600',
                    'https://picsum.photos/seed/abnb6d/800/600',
                    'https://picsum.photos/seed/abnb6e/800/600',
                ],
                'price' => 290,
                'rating' => 4.85,
                'reviewCount' => 89,
                'category' => 'Beachfront',
                'host' => 'Kai',
                'hostAvatarUrl' => 'https://i.pravatar.cc/150?u=abnbhost6',
                'hostIsSuperhost' => true,
                'hostYears' => 5,
                'description' => "A private bungalow steps from white sand beaches. Lanai with ocean views, outdoor shower surrounded by tropical plants, and hammocks swaying in the island breeze.\n\nThe space\nThis charming 1-bedroom bungalow is surrounded by lush tropical gardens. The open-air lanai extends your living space and provides the perfect spot for morning coffee or sunset drinks.\n\nGuest access\nThe entire bungalow and surrounding garden. Shared path to the beach.",
                'amenities' => [
                    ['ios' => Ios::Wifi, 'android' => Android::Wifi, 'label' => 'Wifi'],
                    ['ios' => Ios::RefrigeratorFill, 'android' => Android::Kitchen, 'label' => 'Kitchen'],
                    ['ios' => Ios::Snowflake, 'android' => Android::AcUnit, 'label' => 'Air conditioning'],
                    ['icon' => 'snorkeling', 'label' => 'Snorkel gear'],
                    ['ios' => Ios::Bicycle, 'android' => Android::DirectionsBike, 'label' => 'Bikes included'],
                    ['ios' => Ios::Parkingsign, 'android' => Android::LocalParking, 'label' => 'Free parking on premises'],
                    ['ios' => Ios::BeachUmbrellaFill, 'android' => Android::BeachAccess, 'label' => 'Beach access'],
                    ['ios' => Ios::ShowerFill, 'android' => Android::Shower, 'label' => 'Outdoor shower'],
                    ['ios' => Ios::ChairLoungeFill, 'android' => Android::Deck, 'label' => 'Lanai'],
                    ['ios' => Ios::WasherFill, 'android' => Android::LocalLaundryService, 'label' => 'Washer'],
                ],
                'type' => 'Entire bungalow',
                'guests' => 3,
                'bedrooms' => 1,
                'beds' => 1,
                'bathrooms' => 1,
                'dates' => 'Apr 5–10',
                'distance' => '2,471 miles away',
                'highlights' => [
                    ['ios' => Ios::DoorLeftHandClosed, 'android' => Android::DoorFront, 'title' => 'Self check-in', 'subtitle' => 'Check yourself in with the lockbox.'],
                    ['ios' => Ios::StarFill, 'android' => Android::Star, 'title' => 'Kai is a Superhost', 'subtitle' => 'Superhosts are experienced, highly rated Hosts.'],
                    ['ios' => Ios::CalendarBadgeCheckmark, 'android' => Android::EventAvailable, 'title' => 'Free cancellation before Mar 29', 'subtitle' => ''],
                ],
            ],
            [
                'title' => 'Alpine Chalet with Hot Tub',
                'location' => 'Park City, Utah',
                'imageUrl' => 'https://picsum.photos/seed/abnb7/800/600',
                'images' => [
                    'https://picsum.photos/seed/abnb7/800/600',
                    'https://picsum.photos/seed/abnb7b/800/600',
                    'https://picsum.photos/seed/abnb7c/800/600',
                    'https://picsum.photos/seed/abnb7d/800/600',
                    'https://picsum.photos/seed/abnb7e/800/600',
                ],
                'price' => 310,
                'rating' => 4.75,
                'reviewCount' => 64,
                'category' => 'Amazing views',
                'host' => 'Chris',
                'hostAvatarUrl' => 'https://i.pravatar.cc/150?u=abnbhost7',
                'hostIsSuperhost' => true,
                'hostYears' => 7,
                'description' => "Luxurious ski chalet with panoramic mountain views. Private hot tub, game room, gourmet kitchen, and a cozy reading nook. Minutes from world-class slopes and trails.\n\nThe space\nThis 4-bedroom chalet is designed for comfort and entertainment. The great room features soaring ceilings and a massive stone fireplace. Lower level has a game room with pool table and wet bar.\n\nGuest access\nEntire chalet including garage, hot tub, and game room.",
                'amenities' => [
                    ['ios' => Ios::Wifi, 'android' => Android::Wifi, 'label' => 'Wifi'],
                    ['ios' => Ios::BathtubFill, 'android' => Android::HotTub, 'label' => 'Private hot tub'],
                    ['ios' => Ios::RefrigeratorFill, 'android' => Android::Kitchen, 'label' => 'Kitchen'],
                    ['ios' => Ios::FlameFill, 'android' => Android::Fireplace, 'label' => 'Indoor fireplace'],
                    ['ios' => Ios::Parkingsign, 'android' => Android::LocalParking, 'label' => 'Free parking on premises'],
                    ['ios' => Ios::GamecontrollerFill, 'android' => Android::SportsEsports, 'label' => 'Game room'],
                    ['ios' => Ios::Tv, 'android' => Android::Tv, 'label' => '70" HDTV with streaming'],
                    ['ios' => Ios::ThermometerMedium, 'android' => Android::Thermostat, 'label' => 'Heating'],
                    ['ios' => Ios::FigureSkiingDownhill, 'android' => Android::DownhillSkiing, 'label' => 'Near ski slopes'],
                    ['ios' => Ios::WasherFill, 'android' => Android::LocalLaundryService, 'label' => 'Washer and dryer'],
                ],
                'type' => 'Entire home',
                'guests' => 10,
                'bedrooms' => 4,
                'beds' => 6,
                'bathrooms' => 3,
                'dates' => 'Mar 5–10',
                'distance' => '650 miles away',
                'highlights' => [
                    ['ios' => Ios::DoorLeftHandClosed, 'android' => Android::DoorFront, 'title' => 'Self check-in', 'subtitle' => 'Check yourself in with the smart lock.'],
                    ['ios' => Ios::StarFill, 'android' => Android::Star, 'title' => 'Chris is a Superhost', 'subtitle' => 'Superhosts are experienced, highly rated Hosts.'],
                    ['ios' => Ios::CalendarBadgeCheckmark, 'android' => Android::EventAvailable, 'title' => 'Free cancellation before Feb 26', 'subtitle' => ''],
                ],
            ],
            [
                'title' => 'Stylish City Studio',
                'location' => 'San Francisco, California',
                'imageUrl' => 'https://picsum.photos/seed/abnb8/800/600',
                'images' => [
                    'https://picsum.photos/seed/abnb8/800/600',
                    'https://picsum.photos/seed/abnb8b/800/600',
                    'https://picsum.photos/seed/abnb8c/800/600',
                    'https://picsum.photos/seed/abnb8d/800/600',
                    'https://picsum.photos/seed/abnb8e/800/600',
                ],
                'price' => 145,
                'rating' => 4.5,
                'reviewCount' => 112,
                'category' => 'Trending',
                'host' => 'Lena',
                'hostAvatarUrl' => 'https://i.pravatar.cc/150?u=abnbhost8',
                'hostIsSuperhost' => false,
                'hostYears' => 1,
                'description' => "Bright and modern studio in a vibrant neighborhood. Curated interiors, fast WiFi for remote work, and a rooftop terrace with Golden Gate Bridge views.\n\nThe space\nA thoughtfully designed 500 sq ft studio with a queen bed, full kitchen, and a dedicated work nook by the window. The building has a shared rooftop terrace with stunning views.\n\nGuest access\nEntire studio plus access to shared rooftop terrace and laundry room.",
                'amenities' => [
                    ['ios' => Ios::Wifi, 'android' => Android::Wifi, 'label' => 'Wifi'],
                    ['ios' => Ios::Snowflake, 'android' => Android::AcUnit, 'label' => 'Air conditioning'],
                    ['ios' => Ios::RefrigeratorFill, 'android' => Android::Kitchen, 'label' => 'Kitchen'],
                    ['ios' => Ios::HouseFill, 'android' => Android::Roofing, 'label' => 'Rooftop terrace'],
                    ['ios' => Ios::WasherFill, 'android' => Android::LocalLaundryService, 'label' => 'Washer'],
                    ['ios' => Ios::Laptopcomputer, 'android' => Android::Laptop, 'label' => 'Dedicated workspace'],
                    ['ios' => Ios::Tv, 'android' => Android::Tv, 'label' => '43" Smart TV'],
                    ['ios' => Ios::TshirtFill, 'android' => Android::Iron, 'label' => 'Iron'],
                ],
                'type' => 'Entire guest suite',
                'guests' => 2,
                'bedrooms' => 1,
                'beds' => 1,
                'bathrooms' => 1,
                'dates' => 'Apr 12–17',
                'distance' => '382 miles away',
                'highlights' => [
                    ['ios' => Ios::PhotoFill, 'android' => Android::Landscape, 'title' => 'Great location', 'subtitle' => '100% of recent guests gave the location a 5-star rating.'],
                    ['ios' => Ios::Laptopcomputer, 'android' => Android::Laptop, 'title' => 'Dedicated workspace', 'subtitle' => 'A room with wifi that is well-suited for working.'],
                    ['ios' => Ios::CalendarBadgeCheckmark, 'android' => Android::EventAvailable, 'title' => 'Free cancellation before Apr 5', 'subtitle' => ''],
                ],
            ],
        ];
    }

    /**
     * @return array<int, array{name: string, icon: string}>
     */
    public static function categories(): array
    {
        return [
            ['name' => 'Amazing views', 'ios' => Ios::PhotoFill, 'android' => Android::Landscape],
            ['name' => 'Beachfront', 'ios' => Ios::BeachUmbrellaFill, 'android' => Android::BeachAccess],
            ['name' => 'Cabins', 'ios' => Ios::HouseLodgeFill, 'android' => Android::Cabin],
            ['name' => 'OMG!', 'ios' => Ios::Sparkles, 'android' => Android::AutoAwesome],
            ['name' => 'Trending', 'ios' => Ios::FlameFill, 'android' => Android::LocalFireDepartment],
            ['name' => 'Lakefront', 'ios' => Ios::DropFill, 'android' => Android::Water],
            ['name' => 'Tiny homes', 'ios' => Ios::HouseFill, 'android' => Android::Cottage],
            ['name' => 'Design', 'ios' => Ios::PaintbrushFill, 'android' => Android::DesignServices],
            ['name' => 'Countryside', 'ios' => Ios::LeafFill, 'android' => Android::Grass],
            ['name' => 'Mansions', 'ios' => Ios::HouseFill, 'android' => Android::Villa],
        ];
    }

    /**
     * @return array<int, array<int, array{username: string, avatarUrl: string, date: string, rating: int, text: string}>>
     */
    public static function reviews(): array
    {
        return [
            0 => [
                ['username' => 'Michael', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr1', 'date' => 'January 2026', 'rating' => 5, 'text' => 'Absolutely stunning property. The infinity pool was even better than the photos. Sarah was an incredible host.'],
                ['username' => 'Jessica', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr2', 'date' => 'December 2025', 'rating' => 5, 'text' => 'Best vacation rental we have ever stayed at. The views are unreal and everything was spotlessly clean.'],
                ['username' => 'David', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr3', 'date' => 'November 2025', 'rating' => 5, 'text' => 'Perfect location right on the beach. We did not want to leave. Will definitely be coming back.'],
            ],
            1 => [
                ['username' => 'Rachel', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr4', 'date' => 'February 2026', 'rating' => 5, 'text' => 'The A-frame was magical. Sitting in the hot tub watching snow fall is an experience I will never forget.'],
                ['username' => 'Tom', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr5', 'date' => 'January 2026', 'rating' => 5, 'text' => 'Ski-in/ski-out was so convenient. Cabin was warm, cozy, and had everything we needed.'],
            ],
            2 => [
                ['username' => 'Amanda', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr6', 'date' => 'January 2026', 'rating' => 5, 'text' => 'Lake views were incredible. Kayaking at sunset was the highlight of our trip.'],
                ['username' => 'Brian', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr7', 'date' => 'October 2025', 'rating' => 4, 'text' => 'Great cabin in a beautiful spot. Kitchen was well equipped and the fireplace was so cozy.'],
            ],
            3 => [
                ['username' => 'Sophie', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr8', 'date' => 'February 2026', 'rating' => 5, 'text' => 'Most unique stay ever. Falling asleep among the trees was surreal. Marcus is an amazing host.'],
                ['username' => 'Chris', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr9', 'date' => 'January 2026', 'rating' => 5, 'text' => 'Truly a one-of-a-kind experience. The stargazing from the deck was incredible.'],
                ['username' => 'Nina', 'avatarUrl' => 'https://i.pravatar.cc/150?u=abnbr10', 'date' => 'December 2025', 'rating' => 5, 'text' => 'Words cannot describe how magical this treehouse is. Already planning our return trip.'],
            ],
        ];
    }
}
